apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata: # kpt-merge: /config-management
  name: config-management
  annotations:
    config.kubernetes.io/depends-on: apiextensions.k8s.io/CustomResourceDefinition/configmanagements.configmanagement.gke.io
    internal.kpt.dev/upstream-identifier: 'configmanagement.gke.io|ConfigManagement|default|config-management'
spec:
  enableMultiRepo: true
