apiVersion: v1
kind: Service
metadata: # kpt-merge: nephio-webui/nephio-webui
  name: nephio-webui
  namespace: nephio-webui
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|nephio-webui|nephio-webui'
spec:
  selector:
    app: nephio-webui
  ports:
    - name: http
      port: 7007
      targetPort: http
