apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata: # kpt-merge: /generate-values
  name: generate-values
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: fn.kpt.dev|StarlarkRun|default|generate-values
source: |-
  load("krmfn.star", "krmfn")
  def set_values(resources):
    for r in resources:
      if krmfn.match_gvk(r, "v1", "ConfigMap") and krmfn.match_name(r, "kptfile.kpt.dev"):
        name = r["data"]["name"]
        clusterName = r["data"].get("clusterName", name)
    for r in resources:
      if krmfn.match_gvk(r, "v1", "ConfigMap") and krmfn.match_name(r, "localconfig"):
        name = r["data"]["name"]
        clusterName = r["data"].get("clusterName", name)
    for r in resources:
      if krmfn.match_gvk(r, "cluster.x-k8s.io/v1beta1", "Cluster"):
        r["metadata"]["name"] = clusterName
  set_values(ctx.resource_list["items"])
